add clang scan-build

diff --git a/tools/analyze b/tools/analyze
--- a/tools/analyze
+++ b/tools/analyze
@@ -1,5 +1,6 @@
 #!/bin/bash -e
 
+which scan-build || (echo "can't find clang scan-build"; exit 1)
 which cppcheck || (echo "can't find cppcheck"; exit 1)
 
 if ! [ -e build ]; then mkdir build; fi; cd build
@@ -7,6 +8,8 @@ if ! [ -e build ]; then mkdir build; fi; cd build
 if [ "$1" != "noinit" ]; then
     cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
 else shift; fi
+
+scan-build cmake --build . --clean-first -j$(nproc) # clang analyzer
 
 PLATFORMS="native unix32 unix64 win32A win32W win64"
 LOGFILE=cppcheck/analyze_stderr.log
